### ISSUE TITLE
Include taxonomy nodes for OTUs in studies even if otherwise filtered

### ISSUE THREAD

**Issue by jar398** [mtholder/propinquity#3]
The diagram https://github.com/mtholder/propinquity/blob/master/doc/pipeline-tools.png shows no dataflow from phylo_snapshot to cleaned_ott.

I'm pretty sure we decided we'd keep taxonomy nodes if *either* they were unfiltered *or* they belonged to a source tree. (or, necessarily, if they lie on a path from one to the other.) Unfortunately I can't find this recorded in the minutes.

Could you please either account for this in the pipeline diagram, or add it to the agenda for a future hangout?  Thanks.

**Comment by mtholder** [comment]
added discussion of https://github.com/OpenTreeOfLife/germinator/issues/32 to agenda

**Comment by jar398** [comment]
I'm going senile.  I had looked for germinator #32 and couldn't find it.
